"""Add scale_tier to microservices

Revision ID: 241fd43a0197
Revises: d6956dab6d52
Create Date: 2026-06-14 21:10:08.341181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241fd43a0197'
down_revision: Union[str, Sequence[str], None] = 'd6956dab6d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microservices', sa.Column('scale_tier', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microservices', 'scale_tier')
    # ### end Alembic commands ###
