"""add_technologies_to_microservices

Revision ID: b75caf288a86
Revises: 1b91bdd7e138
Create Date: 2026-06-21 22:49:04.610202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75caf288a86'
down_revision: Union[str, Sequence[str], None] = '1b91bdd7e138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microservices', sa.Column('technologies', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microservices', 'technologies')
    # ### end Alembic commands ###
