"""Add repository table

Revision ID: c144ed060f63
Revises: d3d32d78d29f
Create Date: 2026-06-09 23:54:01.655843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c144ed060f63'
down_revision: Union[str, Sequence[str], None] = 'd3d32d78d29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'repositories',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('project_id', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('microservices', sa.Column('repository_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'microservices', 'repositories', ['repository_id'], ['id'])
    op.drop_column('projects', 'repo_paths')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('repo_paths', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'microservices', type_='foreignkey')
    op.drop_column('microservices', 'repository_id')
    op.drop_table('repositories')
    # ### end Alembic commands ###
