"""add_chat_avatar_fields

Revision ID: ed6bec20ef49
Revises: b75caf288a86
Create Date: 2026-06-21 23:14:10.217715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6bec20ef49'
down_revision: Union[str, Sequence[str], None] = 'b75caf288a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microservices', sa.Column('avatar_chat_visual_prompt', sa.String(), nullable=True))
    op.add_column('microservices', sa.Column('avatar_chat_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microservices', 'avatar_chat_image_url')
    op.drop_column('microservices', 'avatar_chat_visual_prompt')
    # ### end Alembic commands ###
